// this file generated by tools,don't edit it!!!
package configdata

import (
	"fmt"
	"trcell/pkg/configdata/csvdef"
	"trcell/pkg/configdata/csvparse"
)

type CSVModuleMgr struct {
	filePath string
	// --------- csvmodule tag1 begin ------------------
	unionBossModule   *csvdef.UnionBossCfgModule
	unionBossLvModule *csvdef.UnionBossLvCfgModule
	chargeModule      *csvdef.ChargeCfgModule
	formationModule   *csvdef.FormationCfgModule
	drawGuessModule   *csvdef.DrawGuessCfgModule
	undercoverModule  *csvdef.UndercoverCfgModule
	// --------- csvmodule tag1 end --------------------
}

func NewCSVModuleMgr(csvPath string) *CSVModuleMgr {
	return &CSVModuleMgr{
		filePath: csvPath,
		// --------- csvmodule tag2 begin ------------------
		unionBossModule:   csvdef.NewUnionBossCfgModule(),
		unionBossLvModule: csvdef.NewUnionBossLvCfgModule(),
		chargeModule:      csvdef.NewChargeCfgModule(),
		formationModule:   csvdef.NewFormationCfgModule(),
		drawGuessModule:   csvdef.NewDrawGuessCfgModule(),
		undercoverModule:  csvdef.NewUndercoverCfgModule(),
		// --------- csvmodule tag2 end --------------------
	}
}

func (mgr *CSVModuleMgr) LoadAll() {
	// --------- csvmodule tag3 begin ------------------
	// mgr.unionBossModule.Load(csvparse.ParseCsvFileLine(fmt.Sprintf("%s/%s", mgr.filePath, "union_boss.csv")))
	// mgr.unionBossLvModule.Load(csvparse.ParseCsvFileLine(fmt.Sprintf("%s/%s", mgr.filePath, "union_boss_lv.csv")))
	// mgr.chargeModule.Load(csvparse.ParseCsvFileLine(fmt.Sprintf("%s/%s", mgr.filePath, "Charge.csv")))
	// mgr.formationModule.Load(csvparse.ParseCsvFileLine(fmt.Sprintf("%s/%s", mgr.filePath, "Formation.csv")))
	mgr.drawGuessModule.Load(csvparse.ParseCsvFileLine(fmt.Sprintf("%s/%s", mgr.filePath, "draw_guess.csv")))
	mgr.undercoverModule.Load(csvparse.ParseCsvFileLine(fmt.Sprintf("%s/%s", mgr.filePath, "undercover.csv")))
	// --------- csvmodule tag3 end --------------------
}
