// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: proto_rpc/s_rpc_global.proto

package pbrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// echo测试
type EchoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendText string `protobuf:"bytes,1,opt,name=sendText,proto3" json:"sendText,omitempty"`
}

func (x *EchoReq) Reset() {
	*x = EchoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReq) ProtoMessage() {}

func (x *EchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReq.ProtoReflect.Descriptor instead.
func (*EchoReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_global_proto_rawDescGZIP(), []int{0}
}

func (x *EchoReq) GetSendText() string {
	if x != nil {
		return x.SendText
	}
	return ""
}

type EchoRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendText string `protobuf:"bytes,1,opt,name=sendText,proto3" json:"sendText,omitempty"`
}

func (x *EchoRep) Reset() {
	*x = EchoRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRep) ProtoMessage() {}

func (x *EchoRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRep.ProtoReflect.Descriptor instead.
func (*EchoRep) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_global_proto_rawDescGZIP(), []int{1}
}

func (x *EchoRep) GetSendText() string {
	if x != nil {
		return x.SendText
	}
	return ""
}

// 生成uid
type GenUIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *GenUIDReq) Reset() {
	*x = GenUIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUIDReq) ProtoMessage() {}

func (x *GenUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUIDReq.ProtoReflect.Descriptor instead.
func (*GenUIDReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_global_proto_rawDescGZIP(), []int{2}
}

func (x *GenUIDReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GenUIDRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UIDs []int64 `protobuf:"varint,1,rep,packed,name=UIDs,proto3" json:"UIDs,omitempty"`
}

func (x *GenUIDRep) Reset() {
	*x = GenUIDRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUIDRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUIDRep) ProtoMessage() {}

func (x *GenUIDRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_global_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUIDRep.ProtoReflect.Descriptor instead.
func (*GenUIDRep) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_global_proto_rawDescGZIP(), []int{3}
}

func (x *GenUIDRep) GetUIDs() []int64 {
	if x != nil {
		return x.UIDs
	}
	return nil
}

var File_proto_rpc_s_rpc_global_proto protoreflect.FileDescriptor

var file_proto_rpc_s_rpc_global_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x5f, 0x72, 0x70,
	0x63, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x62, 0x72, 0x70, 0x63, 0x22, 0x25, 0x0a, 0x07, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x74, 0x22, 0x25, 0x0a, 0x07,
	0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54,
	0x65, 0x78, 0x74, 0x22, 0x1d, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4e,
	0x75, 0x6d, 0x22, 0x1f, 0x0a, 0x09, 0x47, 0x65, 0x6e, 0x55, 0x49, 0x44, 0x52, 0x65, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x55, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x55,
	0x49, 0x44, 0x73, 0x32, 0x6a, 0x0a, 0x0a, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x2c, 0x0a, 0x08, 0x45, 0x63, 0x68, 0x6f, 0x54, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x2e,
	0x70, 0x62, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x70, 0x62, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12,
	0x2e, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x55, 0x69, 0x64, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x6e, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x55, 0x49, 0x44, 0x52, 0x65, 0x70, 0x22, 0x00, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_rpc_s_rpc_global_proto_rawDescOnce sync.Once
	file_proto_rpc_s_rpc_global_proto_rawDescData = file_proto_rpc_s_rpc_global_proto_rawDesc
)

func file_proto_rpc_s_rpc_global_proto_rawDescGZIP() []byte {
	file_proto_rpc_s_rpc_global_proto_rawDescOnce.Do(func() {
		file_proto_rpc_s_rpc_global_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_s_rpc_global_proto_rawDescData)
	})
	return file_proto_rpc_s_rpc_global_proto_rawDescData
}

var file_proto_rpc_s_rpc_global_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rpc_s_rpc_global_proto_goTypes = []interface{}{
	(*EchoReq)(nil),   // 0: pbrpc.EchoReq
	(*EchoRep)(nil),   // 1: pbrpc.EchoRep
	(*GenUIDReq)(nil), // 2: pbrpc.GenUIDReq
	(*GenUIDRep)(nil), // 3: pbrpc.GenUIDRep
}
var file_proto_rpc_s_rpc_global_proto_depIdxs = []int32{
	0, // 0: pbrpc.GlobalData.EchoTest:input_type -> pbrpc.EchoReq
	2, // 1: pbrpc.GlobalData.GenUid:input_type -> pbrpc.GenUIDReq
	1, // 2: pbrpc.GlobalData.EchoTest:output_type -> pbrpc.EchoRep
	3, // 3: pbrpc.GlobalData.GenUid:output_type -> pbrpc.GenUIDRep
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_s_rpc_global_proto_init() }
func file_proto_rpc_s_rpc_global_proto_init() {
	if File_proto_rpc_s_rpc_global_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_s_rpc_global_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_global_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_global_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_global_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUIDRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_s_rpc_global_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_s_rpc_global_proto_goTypes,
		DependencyIndexes: file_proto_rpc_s_rpc_global_proto_depIdxs,
		MessageInfos:      file_proto_rpc_s_rpc_global_proto_msgTypes,
	}.Build()
	File_proto_rpc_s_rpc_global_proto = out.File
	file_proto_rpc_s_rpc_global_proto_rawDesc = nil
	file_proto_rpc_s_rpc_global_proto_goTypes = nil
	file_proto_rpc_s_rpc_global_proto_depIdxs = nil
}
