// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: proto_rpc/s_rpc_loginqueue.proto

package pbrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取一个序列号
type LoginSeqNoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName string `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"` // 账号名字
}

func (x *LoginSeqNoReq) Reset() {
	*x = LoginSeqNoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginSeqNoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSeqNoReq) ProtoMessage() {}

func (x *LoginSeqNoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSeqNoReq.ProtoReflect.Descriptor instead.
func (*LoginSeqNoReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{0}
}

func (x *LoginSeqNoReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type LoginSeqNoRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNo      int32 `protobuf:"varint,1,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`           // 当前账号对应的排队序列号
	CurQueueNo int32 `protobuf:"varint,2,opt,name=CurQueueNo,proto3" json:"CurQueueNo,omitempty"` // 当前排队的序列号
	QueueNum   int32 `protobuf:"varint,3,opt,name=QueueNum,proto3" json:"QueueNum,omitempty"`     // 当前排队的数量
}

func (x *LoginSeqNoRep) Reset() {
	*x = LoginSeqNoRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginSeqNoRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSeqNoRep) ProtoMessage() {}

func (x *LoginSeqNoRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSeqNoRep.ProtoReflect.Descriptor instead.
func (*LoginSeqNoRep) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{1}
}

func (x *LoginSeqNoRep) GetSeqNo() int32 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *LoginSeqNoRep) GetCurQueueNo() int32 {
	if x != nil {
		return x.CurQueueNo
	}
	return 0
}

func (x *LoginSeqNoRep) GetQueueNum() int32 {
	if x != nil {
		return x.QueueNum
	}
	return 0
}

// 获取当前完成队列号
type QueryCurLoginFinishNoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryCurLoginFinishNoReq) Reset() {
	*x = QueryCurLoginFinishNoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCurLoginFinishNoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCurLoginFinishNoReq) ProtoMessage() {}

func (x *QueryCurLoginFinishNoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCurLoginFinishNoReq.ProtoReflect.Descriptor instead.
func (*QueryCurLoginFinishNoReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{2}
}

type QueryCurLoginFinishNoRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurFinishNo int32 `protobuf:"varint,2,opt,name=CurFinishNo,proto3" json:"CurFinishNo,omitempty"` // 当前完成队列号
}

func (x *QueryCurLoginFinishNoRep) Reset() {
	*x = QueryCurLoginFinishNoRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCurLoginFinishNoRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCurLoginFinishNoRep) ProtoMessage() {}

func (x *QueryCurLoginFinishNoRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCurLoginFinishNoRep.ProtoReflect.Descriptor instead.
func (*QueryCurLoginFinishNoRep) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{3}
}

func (x *QueryCurLoginFinishNoRep) GetCurFinishNo() int32 {
	if x != nil {
		return x.CurFinishNo
	}
	return 0
}

// 更新完成队列号
type IncrementLoginFinishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName string `protobuf:"bytes,1,opt,name=AccountName,proto3" json:"AccountName,omitempty"`
}

func (x *IncrementLoginFinishReq) Reset() {
	*x = IncrementLoginFinishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementLoginFinishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementLoginFinishReq) ProtoMessage() {}

func (x *IncrementLoginFinishReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementLoginFinishReq.ProtoReflect.Descriptor instead.
func (*IncrementLoginFinishReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{4}
}

func (x *IncrementLoginFinishReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type IncrementLoginFinishRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IncrementLoginFinishRep) Reset() {
	*x = IncrementLoginFinishRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementLoginFinishRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementLoginFinishRep) ProtoMessage() {}

func (x *IncrementLoginFinishRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementLoginFinishRep.ProtoReflect.Descriptor instead.
func (*IncrementLoginFinishRep) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{5}
}

// 获取当前排队数量
type GetQueueNumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQueueNumReq) Reset() {
	*x = GetQueueNumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueueNumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueNumReq) ProtoMessage() {}

func (x *GetQueueNumReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueNumReq.ProtoReflect.Descriptor instead.
func (*GetQueueNumReq) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{6}
}

type GetQueueNumRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueueNum int32 `protobuf:"varint,1,opt,name=QueueNum,proto3" json:"QueueNum,omitempty"`
}

func (x *GetQueueNumRep) Reset() {
	*x = GetQueueNumRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQueueNumRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueNumRep) ProtoMessage() {}

func (x *GetQueueNumRep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueNumRep.ProtoReflect.Descriptor instead.
func (*GetQueueNumRep) Descriptor() ([]byte, []int) {
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP(), []int{7}
}

func (x *GetQueueNumRep) GetQueueNum() int32 {
	if x != nil {
		return x.QueueNum
	}
	return 0
}

var File_proto_rpc_s_rpc_loginqueue_proto protoreflect.FileDescriptor

var file_proto_rpc_s_rpc_loginqueue_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x5f, 0x72, 0x70,
	0x63, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x72, 0x70, 0x63, 0x22, 0x31, 0x0a, 0x0d, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x0d,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x52, 0x65, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x65,
	0x71, 0x4e, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x72, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x75, 0x72, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x75, 0x6d, 0x22,
	0x1a, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x75, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x3c, 0x0a, 0x18, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x43, 0x75, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x4e, 0x6f, 0x52, 0x65, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43, 0x75,
	0x72, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x22, 0x3b, 0x0a, 0x17, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x70, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x75, 0x6d,
	0x52, 0x65, 0x71, 0x22, 0x2c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x75,
	0x6d, 0x32, 0xc1, 0x02, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x3d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x70, 0x62, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x4e,
	0x6f, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x53, 0x65, 0x71, 0x4e, 0x6f, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x72, 0x70, 0x63,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x75, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x72, 0x70,
	0x63, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x75, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x6f, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x14,
	0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x70, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70,
	0x62, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x4e, 0x75, 0x6d,
	0x52, 0x65, 0x70, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_s_rpc_loginqueue_proto_rawDescOnce sync.Once
	file_proto_rpc_s_rpc_loginqueue_proto_rawDescData = file_proto_rpc_s_rpc_loginqueue_proto_rawDesc
)

func file_proto_rpc_s_rpc_loginqueue_proto_rawDescGZIP() []byte {
	file_proto_rpc_s_rpc_loginqueue_proto_rawDescOnce.Do(func() {
		file_proto_rpc_s_rpc_loginqueue_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_s_rpc_loginqueue_proto_rawDescData)
	})
	return file_proto_rpc_s_rpc_loginqueue_proto_rawDescData
}

var file_proto_rpc_s_rpc_loginqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_rpc_s_rpc_loginqueue_proto_goTypes = []interface{}{
	(*LoginSeqNoReq)(nil),            // 0: pbrpc.LoginSeqNoReq
	(*LoginSeqNoRep)(nil),            // 1: pbrpc.LoginSeqNoRep
	(*QueryCurLoginFinishNoReq)(nil), // 2: pbrpc.QueryCurLoginFinishNoReq
	(*QueryCurLoginFinishNoRep)(nil), // 3: pbrpc.QueryCurLoginFinishNoRep
	(*IncrementLoginFinishReq)(nil),  // 4: pbrpc.IncrementLoginFinishReq
	(*IncrementLoginFinishRep)(nil),  // 5: pbrpc.IncrementLoginFinishRep
	(*GetQueueNumReq)(nil),           // 6: pbrpc.GetQueueNumReq
	(*GetQueueNumRep)(nil),           // 7: pbrpc.GetQueueNumRep
}
var file_proto_rpc_s_rpc_loginqueue_proto_depIdxs = []int32{
	0, // 0: pbrpc.LoginQueueBackend.GetLoginSeqNo:input_type -> pbrpc.LoginSeqNoReq
	2, // 1: pbrpc.LoginQueueBackend.GetFinishSeqNo:input_type -> pbrpc.QueryCurLoginFinishNoReq
	4, // 2: pbrpc.LoginQueueBackend.IncrementLoginFinish:input_type -> pbrpc.IncrementLoginFinishReq
	6, // 3: pbrpc.LoginQueueBackend.GetQueueNum:input_type -> pbrpc.GetQueueNumReq
	1, // 4: pbrpc.LoginQueueBackend.GetLoginSeqNo:output_type -> pbrpc.LoginSeqNoRep
	3, // 5: pbrpc.LoginQueueBackend.GetFinishSeqNo:output_type -> pbrpc.QueryCurLoginFinishNoRep
	5, // 6: pbrpc.LoginQueueBackend.IncrementLoginFinish:output_type -> pbrpc.IncrementLoginFinishRep
	7, // 7: pbrpc.LoginQueueBackend.GetQueueNum:output_type -> pbrpc.GetQueueNumRep
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_s_rpc_loginqueue_proto_init() }
func file_proto_rpc_s_rpc_loginqueue_proto_init() {
	if File_proto_rpc_s_rpc_loginqueue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginSeqNoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginSeqNoRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCurLoginFinishNoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCurLoginFinishNoRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementLoginFinishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementLoginFinishRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueueNumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_s_rpc_loginqueue_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQueueNumRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_s_rpc_loginqueue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_s_rpc_loginqueue_proto_goTypes,
		DependencyIndexes: file_proto_rpc_s_rpc_loginqueue_proto_depIdxs,
		MessageInfos:      file_proto_rpc_s_rpc_loginqueue_proto_msgTypes,
	}.Build()
	File_proto_rpc_s_rpc_loginqueue_proto = out.File
	file_proto_rpc_s_rpc_loginqueue_proto_rawDesc = nil
	file_proto_rpc_s_rpc_loginqueue_proto_goTypes = nil
	file_proto_rpc_s_rpc_loginqueue_proto_depIdxs = nil
}
