// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: s_db.proto

package pbserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 表数据
type DbTableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableID int32  `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"` // 表id
	Data    []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`        // 数据 tbobj对象
}

func (x *DbTableData) Reset() {
	*x = DbTableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbTableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbTableData) ProtoMessage() {}

func (x *DbTableData) ProtoReflect() protoreflect.Message {
	mi := &file_s_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbTableData.ProtoReflect.Descriptor instead.
func (*DbTableData) Descriptor() ([]byte, []int) {
	return file_s_db_proto_rawDescGZIP(), []int{0}
}

func (x *DbTableData) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

func (x *DbTableData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 表数据列表
type DbTableListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TbData []byte `protobuf:"bytes,1,opt,name=TbData,proto3" json:"TbData,omitempty"` // 数据 单条 tbobj对象
}

func (x *DbTableListItem) Reset() {
	*x = DbTableListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbTableListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbTableListItem) ProtoMessage() {}

func (x *DbTableListItem) ProtoReflect() protoreflect.Message {
	mi := &file_s_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbTableListItem.ProtoReflect.Descriptor instead.
func (*DbTableListItem) Descriptor() ([]byte, []int) {
	return file_s_db_proto_rawDescGZIP(), []int{1}
}

func (x *DbTableListItem) GetTbData() []byte {
	if x != nil {
		return x.TbData
	}
	return nil
}

type DbTableDataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableID  int32              `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"` // 表id
	DataList []*DbTableListItem `protobuf:"bytes,2,rep,name=DataList,proto3" json:"DataList,omitempty"`
}

func (x *DbTableDataList) Reset() {
	*x = DbTableDataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbTableDataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbTableDataList) ProtoMessage() {}

func (x *DbTableDataList) ProtoReflect() protoreflect.Message {
	mi := &file_s_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbTableDataList.ProtoReflect.Descriptor instead.
func (*DbTableDataList) Descriptor() ([]byte, []int) {
	return file_s_db_proto_rawDescGZIP(), []int{2}
}

func (x *DbTableDataList) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

func (x *DbTableDataList) GetDataList() []*DbTableListItem {
	if x != nil {
		return x.DataList
	}
	return nil
}

var File_s_db_proto protoreflect.FileDescriptor

var file_s_db_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0b, 0x44, 0x62, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x0f, 0x44, 0x62, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x62, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x62, 0x44, 0x61, 0x74, 0x61, 0x22, 0x62,
	0x0a, 0x0f, 0x44, 0x62, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x62, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_db_proto_rawDescOnce sync.Once
	file_s_db_proto_rawDescData = file_s_db_proto_rawDesc
)

func file_s_db_proto_rawDescGZIP() []byte {
	file_s_db_proto_rawDescOnce.Do(func() {
		file_s_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_db_proto_rawDescData)
	})
	return file_s_db_proto_rawDescData
}

var file_s_db_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_s_db_proto_goTypes = []interface{}{
	(*DbTableData)(nil),     // 0: pbserver.DbTableData
	(*DbTableListItem)(nil), // 1: pbserver.DbTableListItem
	(*DbTableDataList)(nil), // 2: pbserver.DbTableDataList
}
var file_s_db_proto_depIdxs = []int32{
	1, // 0: pbserver.DbTableDataList.DataList:type_name -> pbserver.DbTableListItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_s_db_proto_init() }
func file_s_db_proto_init() {
	if File_s_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbTableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbTableListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbTableDataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s_db_proto_goTypes,
		DependencyIndexes: file_s_db_proto_depIdxs,
		MessageInfos:      file_s_db_proto_msgTypes,
	}.Build()
	File_s_db_proto = out.File
	file_s_db_proto_rawDesc = nil
	file_s_db_proto_goTypes = nil
	file_s_db_proto_depIdxs = nil
}
