// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: s_player.proto

package pbserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	pbclient "trcell/pkg/pb/pbclient"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色数据
type GameRoleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleTables []*DbTableData `protobuf:"bytes,1,rep,name=RoleTables,proto3" json:"RoleTables,omitempty"` // 角色相关的表
}

func (x *GameRoleData) Reset() {
	*x = GameRoleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRoleData) ProtoMessage() {}

func (x *GameRoleData) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRoleData.ProtoReflect.Descriptor instead.
func (*GameRoleData) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{0}
}

func (x *GameRoleData) GetRoleTables() []*DbTableData {
	if x != nil {
		return x.RoleTables
	}
	return nil
}

// 创角数据
type CreateRoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	CchId   string `protobuf:"bytes,2,opt,name=CchId,proto3" json:"CchId,omitempty"`
	Level   int32  `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	UserID  int64  `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *CreateRoleInfo) Reset() {
	*x = CreateRoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleInfo) ProtoMessage() {}

func (x *CreateRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleInfo.ProtoReflect.Descriptor instead.
func (*CreateRoleInfo) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateRoleInfo) GetCchId() string {
	if x != nil {
		return x.CchId
	}
	return ""
}

func (x *CreateRoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateRoleInfo) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

// ESMsgPlayerLoadRole = 1 // 加载角色数据
type ESMsgPlayerLoadRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID   int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	IsLogin  bool   `protobuf:"varint,2,opt,name=IsLogin,proto3" json:"IsLogin,omitempty"` // 是否登录加载
	UserID   int64  `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName string `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"` // CreateRoleInfo CreateParam = 5; // 创角参数
}

func (x *ESMsgPlayerLoadRoleReq) Reset() {
	*x = ESMsgPlayerLoadRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoadRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoadRoleReq) ProtoMessage() {}

func (x *ESMsgPlayerLoadRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoadRoleReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoadRoleReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{2}
}

func (x *ESMsgPlayerLoadRoleReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerLoadRoleReq) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *ESMsgPlayerLoadRoleReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ESMsgPlayerLoadRoleReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ESMsgPlayerLoadRoleRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleDetailData *GameRoleData `protobuf:"bytes,1,opt,name=RoleDetailData,proto3" json:"RoleDetailData,omitempty"` // 角色详细数据
	RoleID         int64         `protobuf:"varint,2,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
}

func (x *ESMsgPlayerLoadRoleRep) Reset() {
	*x = ESMsgPlayerLoadRoleRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoadRoleRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoadRoleRep) ProtoMessage() {}

func (x *ESMsgPlayerLoadRoleRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoadRoleRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoadRoleRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{3}
}

func (x *ESMsgPlayerLoadRoleRep) GetRoleDetailData() *GameRoleData {
	if x != nil {
		return x.RoleDetailData
	}
	return nil
}

func (x *ESMsgPlayerLoadRoleRep) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

// ESMsgPlayerSaveRole = 2 // 保存角色数据
type ESMsgPlayerSaveRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID     int64          `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	RoleTables []*DbTableData `protobuf:"bytes,2,rep,name=RoleTables,proto3" json:"RoleTables,omitempty"` // 角色要保存的相关的表
}

func (x *ESMsgPlayerSaveRoleReq) Reset() {
	*x = ESMsgPlayerSaveRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerSaveRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerSaveRoleReq) ProtoMessage() {}

func (x *ESMsgPlayerSaveRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerSaveRoleReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerSaveRoleReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{4}
}

func (x *ESMsgPlayerSaveRoleReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerSaveRoleReq) GetRoleTables() []*DbTableData {
	if x != nil {
		return x.RoleTables
	}
	return nil
}

type ESMsgPlayerSaveRoleRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgPlayerSaveRoleRep) Reset() {
	*x = ESMsgPlayerSaveRoleRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerSaveRoleRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerSaveRoleRep) ProtoMessage() {}

func (x *ESMsgPlayerSaveRoleRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerSaveRoleRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerSaveRoleRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{5}
}

// ESMsgPlayerLoginGame = 3 // 登录游戏
type ESMsgPlayerLoginGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64           `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`    // 账号id
	Account  string          `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`   // 账号
	CchId    string          `protobuf:"bytes,3,opt,name=CchId,proto3" json:"CchId,omitempty"`       // 渠道
	GateInfo *ServerNodeInfo `protobuf:"bytes,4,opt,name=GateInfo,proto3" json:"GateInfo,omitempty"` // 网关信息
	RoleID   int64           `protobuf:"varint,5,opt,name=RoleID,proto3" json:"RoleID,omitempty"`    // 角色id
}

func (x *ESMsgPlayerLoginGameReq) Reset() {
	*x = ESMsgPlayerLoginGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoginGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoginGameReq) ProtoMessage() {}

func (x *ESMsgPlayerLoginGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoginGameReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoginGameReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{6}
}

func (x *ESMsgPlayerLoginGameReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ESMsgPlayerLoginGameReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ESMsgPlayerLoginGameReq) GetCchId() string {
	if x != nil {
		return x.CchId
	}
	return ""
}

func (x *ESMsgPlayerLoginGameReq) GetGateInfo() *ServerNodeInfo {
	if x != nil {
		return x.GateInfo
	}
	return nil
}

func (x *ESMsgPlayerLoginGameReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

type ESMsgPlayerLoginGameRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleData  *pbclient.RoleInfo `protobuf:"bytes,1,opt,name=RoleData,proto3" json:"RoleData,omitempty"`
	LogicInfo *ServerNodeInfo    `protobuf:"bytes,2,opt,name=LogicInfo,proto3" json:"LogicInfo,omitempty"` // 网关信息
	DataInfo  *ServerNodeInfo    `protobuf:"bytes,3,opt,name=DataInfo,proto3" json:"DataInfo,omitempty"`   // data信息
}

func (x *ESMsgPlayerLoginGameRep) Reset() {
	*x = ESMsgPlayerLoginGameRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerLoginGameRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerLoginGameRep) ProtoMessage() {}

func (x *ESMsgPlayerLoginGameRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerLoginGameRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerLoginGameRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{7}
}

func (x *ESMsgPlayerLoginGameRep) GetRoleData() *pbclient.RoleInfo {
	if x != nil {
		return x.RoleData
	}
	return nil
}

func (x *ESMsgPlayerLoginGameRep) GetLogicInfo() *ServerNodeInfo {
	if x != nil {
		return x.LogicInfo
	}
	return nil
}

func (x *ESMsgPlayerLoginGameRep) GetDataInfo() *ServerNodeInfo {
	if x != nil {
		return x.DataInfo
	}
	return nil
}

// ESMsgPlayerDisconnect = 4 // 玩家连接断开
type ESMsgPlayerDisconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Reason int32 `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"` // 断开原因
}

func (x *ESMsgPlayerDisconnectReq) Reset() {
	*x = ESMsgPlayerDisconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerDisconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerDisconnectReq) ProtoMessage() {}

func (x *ESMsgPlayerDisconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerDisconnectReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerDisconnectReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{8}
}

func (x *ESMsgPlayerDisconnectReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerDisconnectReq) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// ESMsgPlayerDisconnect = 4 // 玩家连接断开
type ESMsgPlayerDisconnectRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgPlayerDisconnectRep) Reset() {
	*x = ESMsgPlayerDisconnectRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerDisconnectRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerDisconnectRep) ProtoMessage() {}

func (x *ESMsgPlayerDisconnectRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerDisconnectRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerDisconnectRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{9}
}

// ESMsgPlayerKickOut    = 5 // 踢掉玩家
type ESMsgPlayerKickOutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID int64 `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	Reason int32 `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *ESMsgPlayerKickOutReq) Reset() {
	*x = ESMsgPlayerKickOutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerKickOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerKickOutReq) ProtoMessage() {}

func (x *ESMsgPlayerKickOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerKickOutReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerKickOutReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{10}
}

func (x *ESMsgPlayerKickOutReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *ESMsgPlayerKickOutReq) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type ESMsgPlayerKickOutRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ESMsgPlayerKickOutRep) Reset() {
	*x = ESMsgPlayerKickOutRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerKickOutRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerKickOutRep) ProtoMessage() {}

func (x *ESMsgPlayerKickOutRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerKickOutRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerKickOutRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{11}
}

// ESMsgPlayerCreateRole = 6 // 玩家创角
type ESMsgPlayerCreateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64           `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName string          `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"` // 账号名字
	Nickname string          `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"` // 角色昵称
	GateInfo *ServerNodeInfo `protobuf:"bytes,4,opt,name=GateInfo,proto3" json:"GateInfo,omitempty"` // 网关信息
}

func (x *ESMsgPlayerCreateRoleReq) Reset() {
	*x = ESMsgPlayerCreateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerCreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerCreateRoleReq) ProtoMessage() {}

func (x *ESMsgPlayerCreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerCreateRoleReq.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerCreateRoleReq) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{12}
}

func (x *ESMsgPlayerCreateRoleReq) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ESMsgPlayerCreateRoleReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ESMsgPlayerCreateRoleReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ESMsgPlayerCreateRoleReq) GetGateInfo() *ServerNodeInfo {
	if x != nil {
		return x.GateInfo
	}
	return nil
}

type ESMsgPlayerCreateRoleRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleData   *pbclient.RoleInfo `protobuf:"bytes,1,opt,name=RoleData,proto3" json:"RoleData,omitempty"`     // 客户端角色数据
	RoleDetail *GameRoleData      `protobuf:"bytes,2,opt,name=RoleDetail,proto3" json:"RoleDetail,omitempty"` // 服务器角色详情数据
	LogicInfo  *ServerNodeInfo    `protobuf:"bytes,3,opt,name=LogicInfo,proto3" json:"LogicInfo,omitempty"`   // 服务器信息
	DataInfo   *ServerNodeInfo    `protobuf:"bytes,4,opt,name=DataInfo,proto3" json:"DataInfo,omitempty"`     // 服务器信息
}

func (x *ESMsgPlayerCreateRoleRep) Reset() {
	*x = ESMsgPlayerCreateRoleRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_player_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESMsgPlayerCreateRoleRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESMsgPlayerCreateRoleRep) ProtoMessage() {}

func (x *ESMsgPlayerCreateRoleRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_player_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESMsgPlayerCreateRoleRep.ProtoReflect.Descriptor instead.
func (*ESMsgPlayerCreateRoleRep) Descriptor() ([]byte, []int) {
	return file_s_player_proto_rawDescGZIP(), []int{13}
}

func (x *ESMsgPlayerCreateRoleRep) GetRoleData() *pbclient.RoleInfo {
	if x != nil {
		return x.RoleData
	}
	return nil
}

func (x *ESMsgPlayerCreateRoleRep) GetRoleDetail() *GameRoleData {
	if x != nil {
		return x.RoleDetail
	}
	return nil
}

func (x *ESMsgPlayerCreateRoleRep) GetLogicInfo() *ServerNodeInfo {
	if x != nil {
		return x.LogicInfo
	}
	return nil
}

func (x *ESMsgPlayerCreateRoleRep) GetDataInfo() *ServerNodeInfo {
	if x != nil {
		return x.DataInfo
	}
	return nil
}

var File_s_player_proto protoreflect.FileDescriptor

var file_s_player_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x73, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x44, 0x62, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a,
	0x52, 0x6f, 0x6c, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x63, 0x68, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x63, 0x68, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x7e, 0x0a, 0x16, 0x45, 0x53,
	0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x49, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49,
	0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x70, 0x0a, 0x16, 0x45, 0x53,
	0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x70, 0x12, 0x3e, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x67, 0x0a, 0x16,
	0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x35,
	0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x62,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x22,
	0xaf, 0x01, 0x0a, 0x17, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x63, 0x68, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x63,
	0x68, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x22, 0xb7, 0x01, 0x0a, 0x17, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x12, 0x2e, 0x0a,
	0x08, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x4c, 0x6f, 0x67, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4a, 0x0a, 0x18, 0x45,
	0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x18, 0x45, 0x53, 0x4d, 0x73, 0x67,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x70, 0x22, 0x47, 0x0a, 0x15, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15,
	0x45, 0x53, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4b, 0x69, 0x63, 0x6b, 0x4f,
	0x75, 0x74, 0x52, 0x65, 0x70, 0x22, 0xa0, 0x01, 0x0a, 0x18, 0x45, 0x53, 0x4d, 0x73, 0x67, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x18, 0x45, 0x53, 0x4d,
	0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x12, 0x2e, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x52, 0x6f, 0x6c,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x36, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x4c, 0x6f, 0x67, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x70, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_s_player_proto_rawDescOnce sync.Once
	file_s_player_proto_rawDescData = file_s_player_proto_rawDesc
)

func file_s_player_proto_rawDescGZIP() []byte {
	file_s_player_proto_rawDescOnce.Do(func() {
		file_s_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_player_proto_rawDescData)
	})
	return file_s_player_proto_rawDescData
}

var file_s_player_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_s_player_proto_goTypes = []interface{}{
	(*GameRoleData)(nil),             // 0: pbserver.GameRoleData
	(*CreateRoleInfo)(nil),           // 1: pbserver.CreateRoleInfo
	(*ESMsgPlayerLoadRoleReq)(nil),   // 2: pbserver.ESMsgPlayerLoadRoleReq
	(*ESMsgPlayerLoadRoleRep)(nil),   // 3: pbserver.ESMsgPlayerLoadRoleRep
	(*ESMsgPlayerSaveRoleReq)(nil),   // 4: pbserver.ESMsgPlayerSaveRoleReq
	(*ESMsgPlayerSaveRoleRep)(nil),   // 5: pbserver.ESMsgPlayerSaveRoleRep
	(*ESMsgPlayerLoginGameReq)(nil),  // 6: pbserver.ESMsgPlayerLoginGameReq
	(*ESMsgPlayerLoginGameRep)(nil),  // 7: pbserver.ESMsgPlayerLoginGameRep
	(*ESMsgPlayerDisconnectReq)(nil), // 8: pbserver.ESMsgPlayerDisconnectReq
	(*ESMsgPlayerDisconnectRep)(nil), // 9: pbserver.ESMsgPlayerDisconnectRep
	(*ESMsgPlayerKickOutReq)(nil),    // 10: pbserver.ESMsgPlayerKickOutReq
	(*ESMsgPlayerKickOutRep)(nil),    // 11: pbserver.ESMsgPlayerKickOutRep
	(*ESMsgPlayerCreateRoleReq)(nil), // 12: pbserver.ESMsgPlayerCreateRoleReq
	(*ESMsgPlayerCreateRoleRep)(nil), // 13: pbserver.ESMsgPlayerCreateRoleRep
	(*DbTableData)(nil),              // 14: pbserver.DbTableData
	(*ServerNodeInfo)(nil),           // 15: pbserver.ServerNodeInfo
	(*pbclient.RoleInfo)(nil),        // 16: pbclient.RoleInfo
}
var file_s_player_proto_depIdxs = []int32{
	14, // 0: pbserver.GameRoleData.RoleTables:type_name -> pbserver.DbTableData
	0,  // 1: pbserver.ESMsgPlayerLoadRoleRep.RoleDetailData:type_name -> pbserver.GameRoleData
	14, // 2: pbserver.ESMsgPlayerSaveRoleReq.RoleTables:type_name -> pbserver.DbTableData
	15, // 3: pbserver.ESMsgPlayerLoginGameReq.GateInfo:type_name -> pbserver.ServerNodeInfo
	16, // 4: pbserver.ESMsgPlayerLoginGameRep.RoleData:type_name -> pbclient.RoleInfo
	15, // 5: pbserver.ESMsgPlayerLoginGameRep.LogicInfo:type_name -> pbserver.ServerNodeInfo
	15, // 6: pbserver.ESMsgPlayerLoginGameRep.DataInfo:type_name -> pbserver.ServerNodeInfo
	15, // 7: pbserver.ESMsgPlayerCreateRoleReq.GateInfo:type_name -> pbserver.ServerNodeInfo
	16, // 8: pbserver.ESMsgPlayerCreateRoleRep.RoleData:type_name -> pbclient.RoleInfo
	0,  // 9: pbserver.ESMsgPlayerCreateRoleRep.RoleDetail:type_name -> pbserver.GameRoleData
	15, // 10: pbserver.ESMsgPlayerCreateRoleRep.LogicInfo:type_name -> pbserver.ServerNodeInfo
	15, // 11: pbserver.ESMsgPlayerCreateRoleRep.DataInfo:type_name -> pbserver.ServerNodeInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_s_player_proto_init() }
func file_s_player_proto_init() {
	if File_s_player_proto != nil {
		return
	}
	file_s_db_proto_init()
	file_s_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_s_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRoleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoadRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoadRoleRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerSaveRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerSaveRoleRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoginGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerLoginGameRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerDisconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerDisconnectRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerKickOutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerKickOutRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerCreateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_player_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ESMsgPlayerCreateRoleRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_player_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s_player_proto_goTypes,
		DependencyIndexes: file_s_player_proto_depIdxs,
		MessageInfos:      file_s_player_proto_msgTypes,
	}.Build()
	File_s_player_proto = out.File
	file_s_player_proto_rawDesc = nil
	file_s_player_proto_goTypes = nil
	file_s_player_proto_depIdxs = nil
}
