// --- this file generated by tools, don't edit it!!!! ---

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: role_base_ormpb.proto

package pborm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID      int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	UserID      int64  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RoleName    string `protobuf:"bytes,3,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	CreateTime  int64  `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Level       int32  `protobuf:"varint,5,opt,name=Level,proto3" json:"Level,omitempty"`
	LoginTime   int64  `protobuf:"varint,6,opt,name=LoginTime,proto3" json:"LoginTime,omitempty"`
	OfflineTime int64  `protobuf:"varint,7,opt,name=OfflineTime,proto3" json:"OfflineTime,omitempty"`
	UpdTime     int64  `protobuf:"varint,8,opt,name=UpdTime,proto3" json:"UpdTime,omitempty"`
	DbStatus    int32  `protobuf:"varint,9,opt,name=DbStatus,proto3" json:"DbStatus,omitempty"`
}

func (x *RoleBase) Reset() {
	*x = RoleBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_base_ormpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBase) ProtoMessage() {}

func (x *RoleBase) ProtoReflect() protoreflect.Message {
	mi := &file_role_base_ormpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBase.ProtoReflect.Descriptor instead.
func (*RoleBase) Descriptor() ([]byte, []int) {
	return file_role_base_ormpb_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBase) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *RoleBase) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RoleBase) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleBase) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RoleBase) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleBase) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *RoleBase) GetOfflineTime() int64 {
	if x != nil {
		return x.OfflineTime
	}
	return 0
}

func (x *RoleBase) GetUpdTime() int64 {
	if x != nil {
		return x.UpdTime
	}
	return 0
}

func (x *RoleBase) GetDbStatus() int32 {
	if x != nil {
		return x.DbStatus
	}
	return 0
}

var File_role_base_ormpb_proto protoreflect.FileDescriptor

var file_role_base_ormpb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6f, 0x72, 0x6d, 0x70,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x62, 0x6f, 0x72, 0x6d, 0x22, 0x82,
	0x02, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x52,
	0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52,
	0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x55, 0x70, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x55, 0x70, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x62, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x62, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x6f, 0x72, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_role_base_ormpb_proto_rawDescOnce sync.Once
	file_role_base_ormpb_proto_rawDescData = file_role_base_ormpb_proto_rawDesc
)

func file_role_base_ormpb_proto_rawDescGZIP() []byte {
	file_role_base_ormpb_proto_rawDescOnce.Do(func() {
		file_role_base_ormpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_role_base_ormpb_proto_rawDescData)
	})
	return file_role_base_ormpb_proto_rawDescData
}

var file_role_base_ormpb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_role_base_ormpb_proto_goTypes = []interface{}{
	(*RoleBase)(nil), // 0: pborm.RoleBase
}
var file_role_base_ormpb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_base_ormpb_proto_init() }
func file_role_base_ormpb_proto_init() {
	if File_role_base_ormpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_role_base_ormpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_role_base_ormpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_base_ormpb_proto_goTypes,
		DependencyIndexes: file_role_base_ormpb_proto_depIdxs,
		MessageInfos:      file_role_base_ormpb_proto_msgTypes,
	}.Build()
	File_role_base_ormpb_proto = out.File
	file_role_base_ormpb_proto_rawDesc = nil
	file_role_base_ormpb_proto_goTypes = nil
	file_role_base_ormpb_proto_depIdxs = nil
}
