// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: c_base.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ECMsgClassCommon = 1 // 通用类别
type ECMsgBasePushErrorOptNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode   int32    `protobuf:"varint,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`    // 错误码
	ErrParams []string `protobuf:"bytes,2,rep,name=ErrParams,proto3" json:"ErrParams,omitempty"` // 错误码参数列表(某些错误提示需要特定参数)
	MsgClass  int32    `protobuf:"varint,3,opt,name=MsgClass,proto3" json:"MsgClass,omitempty"`  // 对应的消息大类型
	MsgType   int32    `protobuf:"varint,4,opt,name=MsgType,proto3" json:"MsgType,omitempty"`    // 对应的消息小类型
}

func (x *ECMsgBasePushErrorOptNotify) Reset() {
	*x = ECMsgBasePushErrorOptNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ECMsgBasePushErrorOptNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECMsgBasePushErrorOptNotify) ProtoMessage() {}

func (x *ECMsgBasePushErrorOptNotify) ProtoReflect() protoreflect.Message {
	mi := &file_c_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECMsgBasePushErrorOptNotify.ProtoReflect.Descriptor instead.
func (*ECMsgBasePushErrorOptNotify) Descriptor() ([]byte, []int) {
	return file_c_base_proto_rawDescGZIP(), []int{0}
}

func (x *ECMsgBasePushErrorOptNotify) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *ECMsgBasePushErrorOptNotify) GetErrParams() []string {
	if x != nil {
		return x.ErrParams
	}
	return nil
}

func (x *ECMsgBasePushErrorOptNotify) GetMsgClass() int32 {
	if x != nil {
		return x.MsgClass
	}
	return 0
}

func (x *ECMsgBasePushErrorOptNotify) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

var File_c_base_proto protoreflect.FileDescriptor

var file_c_base_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x1b, 0x45, 0x43, 0x4d,
	0x73, 0x67, 0x42, 0x61, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4f,
	0x70, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x45, 0x72, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x4d, 0x73, 0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x74, 0x72, 0x63, 0x65, 0x6c, 0x6c,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c_base_proto_rawDescOnce sync.Once
	file_c_base_proto_rawDescData = file_c_base_proto_rawDesc
)

func file_c_base_proto_rawDescGZIP() []byte {
	file_c_base_proto_rawDescOnce.Do(func() {
		file_c_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_base_proto_rawDescData)
	})
	return file_c_base_proto_rawDescData
}

var file_c_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_c_base_proto_goTypes = []interface{}{
	(*ECMsgBasePushErrorOptNotify)(nil), // 0: pbclient.ECMsgBasePushErrorOptNotify
}
var file_c_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c_base_proto_init() }
func file_c_base_proto_init() {
	if File_c_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ECMsgBasePushErrorOptNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_base_proto_goTypes,
		DependencyIndexes: file_c_base_proto_depIdxs,
		MessageInfos:      file_c_base_proto_msgTypes,
	}.Build()
	File_c_base_proto = out.File
	file_c_base_proto_rawDesc = nil
	file_c_base_proto_goTypes = nil
	file_c_base_proto_depIdxs = nil
}
