// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: c_misc.proto

package pbclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 杂项基本信息
type MiscDataInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceInfo string `protobuf:"bytes,1,opt,name=DeviceInfo,proto3" json:"DeviceInfo,omitempty"` // 设备信息
}

func (x *MiscDataInfo) Reset() {
	*x = MiscDataInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_c_misc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MiscDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiscDataInfo) ProtoMessage() {}

func (x *MiscDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_c_misc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiscDataInfo.ProtoReflect.Descriptor instead.
func (*MiscDataInfo) Descriptor() ([]byte, []int) {
	return file_c_misc_proto_rawDescGZIP(), []int{0}
}

func (x *MiscDataInfo) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

var File_c_misc_proto protoreflect.FileDescriptor

var file_c_misc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x5f, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x62, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x0c, 0x4d, 0x69, 0x73, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x62,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_c_misc_proto_rawDescOnce sync.Once
	file_c_misc_proto_rawDescData = file_c_misc_proto_rawDesc
)

func file_c_misc_proto_rawDescGZIP() []byte {
	file_c_misc_proto_rawDescOnce.Do(func() {
		file_c_misc_proto_rawDescData = protoimpl.X.CompressGZIP(file_c_misc_proto_rawDescData)
	})
	return file_c_misc_proto_rawDescData
}

var file_c_misc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_c_misc_proto_goTypes = []interface{}{
	(*MiscDataInfo)(nil), // 0: pbclient.MiscDataInfo
}
var file_c_misc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_c_misc_proto_init() }
func file_c_misc_proto_init() {
	if File_c_misc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_c_misc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MiscDataInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_c_misc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c_misc_proto_goTypes,
		DependencyIndexes: file_c_misc_proto_depIdxs,
		MessageInfos:      file_c_misc_proto_msgTypes,
	}.Build()
	File_c_misc_proto = out.File
	file_c_misc_proto_rawDesc = nil
	file_c_misc_proto_goTypes = nil
	file_c_misc_proto_depIdxs = nil
}
