// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: s_frame.proto

package pbframe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误参数列表
type SErrorParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamList  []string `protobuf:"bytes,1,rep,name=ParamList,proto3" json:"ParamList,omitempty"`
	ErrDesInfo string   `protobuf:"bytes,2,opt,name=ErrDesInfo,proto3" json:"ErrDesInfo,omitempty"`
}

func (x *SErrorParams) Reset() {
	*x = SErrorParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SErrorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SErrorParams) ProtoMessage() {}

func (x *SErrorParams) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SErrorParams.ProtoReflect.Descriptor instead.
func (*SErrorParams) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{0}
}

func (x *SErrorParams) GetParamList() []string {
	if x != nil {
		return x.ParamList
	}
	return nil
}

func (x *SErrorParams) GetErrDesInfo() string {
	if x != nil {
		return x.ErrDesInfo
	}
	return ""
}

// 错误详情定义
type SErrorDetailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode   int32    `protobuf:"varint,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`    // 错误码
	ErrParams []string `protobuf:"bytes,2,rep,name=ErrParams,proto3" json:"ErrParams,omitempty"` // 错误码参数列表(某些错误提示需要特定参数)
	MsgClass  int32    `protobuf:"varint,3,opt,name=MsgClass,proto3" json:"MsgClass,omitempty"`  // 对应的消息大类型
	MsgType   int32    `protobuf:"varint,4,opt,name=MsgType,proto3" json:"MsgType,omitempty"`    // 对应的消息小类型
}

func (x *SErrorDetailInfo) Reset() {
	*x = SErrorDetailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SErrorDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SErrorDetailInfo) ProtoMessage() {}

func (x *SErrorDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SErrorDetailInfo.ProtoReflect.Descriptor instead.
func (*SErrorDetailInfo) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{1}
}

func (x *SErrorDetailInfo) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *SErrorDetailInfo) GetErrParams() []string {
	if x != nil {
		return x.ErrParams
	}
	return nil
}

func (x *SErrorDetailInfo) GetMsgClass() int32 {
	if x != nil {
		return x.MsgClass
	}
	return 0
}

func (x *SErrorDetailInfo) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

// EFrameMsgRegisterServerInfo int32 = 1 // 注册服务信息
type FrameMsgRegisterServerInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZoneID    int32  `protobuf:"varint,1,opt,name=ZoneID,proto3" json:"ZoneID,omitempty"`
	NodeType  int32  `protobuf:"varint,2,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	NodeIndex int32  `protobuf:"varint,3,opt,name=NodeIndex,proto3" json:"NodeIndex,omitempty"`
	NodeDes   string `protobuf:"bytes,4,opt,name=NodeDes,proto3" json:"NodeDes,omitempty"`
}

func (x *FrameMsgRegisterServerInfoReq) Reset() {
	*x = FrameMsgRegisterServerInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameMsgRegisterServerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMsgRegisterServerInfoReq) ProtoMessage() {}

func (x *FrameMsgRegisterServerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMsgRegisterServerInfoReq.ProtoReflect.Descriptor instead.
func (*FrameMsgRegisterServerInfoReq) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{2}
}

func (x *FrameMsgRegisterServerInfoReq) GetZoneID() int32 {
	if x != nil {
		return x.ZoneID
	}
	return 0
}

func (x *FrameMsgRegisterServerInfoReq) GetNodeType() int32 {
	if x != nil {
		return x.NodeType
	}
	return 0
}

func (x *FrameMsgRegisterServerInfoReq) GetNodeIndex() int32 {
	if x != nil {
		return x.NodeIndex
	}
	return 0
}

func (x *FrameMsgRegisterServerInfoReq) GetNodeDes() string {
	if x != nil {
		return x.NodeDes
	}
	return ""
}

type FrameMsgRegisterServerInfoRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FrameMsgRegisterServerInfoRep) Reset() {
	*x = FrameMsgRegisterServerInfoRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameMsgRegisterServerInfoRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMsgRegisterServerInfoRep) ProtoMessage() {}

func (x *FrameMsgRegisterServerInfoRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMsgRegisterServerInfoRep.ProtoReflect.Descriptor instead.
func (*FrameMsgRegisterServerInfoRep) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{3}
}

// EFrameMsgServerMsgConvert   int32 = 3 // 服务器消息转换
type EFrameMsgServerMsgConvertReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgClass int32  `protobuf:"varint,1,opt,name=MsgClass,proto3" json:"MsgClass,omitempty"`
	MsgType  int32  `protobuf:"varint,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MsgData  []byte `protobuf:"bytes,3,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
}

func (x *EFrameMsgServerMsgConvertReq) Reset() {
	*x = EFrameMsgServerMsgConvertReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EFrameMsgServerMsgConvertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EFrameMsgServerMsgConvertReq) ProtoMessage() {}

func (x *EFrameMsgServerMsgConvertReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EFrameMsgServerMsgConvertReq.ProtoReflect.Descriptor instead.
func (*EFrameMsgServerMsgConvertReq) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{4}
}

func (x *EFrameMsgServerMsgConvertReq) GetMsgClass() int32 {
	if x != nil {
		return x.MsgClass
	}
	return 0
}

func (x *EFrameMsgServerMsgConvertReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EFrameMsgServerMsgConvertReq) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

type EFrameMsgServerMsgConvertRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgClass int32  `protobuf:"varint,1,opt,name=MsgClass,proto3" json:"MsgClass,omitempty"`
	MsgType  int32  `protobuf:"varint,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MsgData  []byte `protobuf:"bytes,3,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
}

func (x *EFrameMsgServerMsgConvertRep) Reset() {
	*x = EFrameMsgServerMsgConvertRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EFrameMsgServerMsgConvertRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EFrameMsgServerMsgConvertRep) ProtoMessage() {}

func (x *EFrameMsgServerMsgConvertRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EFrameMsgServerMsgConvertRep.ProtoReflect.Descriptor instead.
func (*EFrameMsgServerMsgConvertRep) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{5}
}

func (x *EFrameMsgServerMsgConvertRep) GetMsgClass() int32 {
	if x != nil {
		return x.MsgClass
	}
	return 0
}

func (x *EFrameMsgServerMsgConvertRep) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EFrameMsgServerMsgConvertRep) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

// EFrameMsgPushMsgToClient    int32 = 4 // 推送消息给玩家
type EFrameMsgPushMsgToClientReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID   int64  `protobuf:"varint,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	MsgType  int32  `protobuf:"varint,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MsgClass int32  `protobuf:"varint,3,opt,name=MsgClass,proto3" json:"MsgClass,omitempty"`
	MsgData  []byte `protobuf:"bytes,4,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
}

func (x *EFrameMsgPushMsgToClientReq) Reset() {
	*x = EFrameMsgPushMsgToClientReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EFrameMsgPushMsgToClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EFrameMsgPushMsgToClientReq) ProtoMessage() {}

func (x *EFrameMsgPushMsgToClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EFrameMsgPushMsgToClientReq.ProtoReflect.Descriptor instead.
func (*EFrameMsgPushMsgToClientReq) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{6}
}

func (x *EFrameMsgPushMsgToClientReq) GetRoleID() int64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *EFrameMsgPushMsgToClientReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EFrameMsgPushMsgToClientReq) GetMsgClass() int32 {
	if x != nil {
		return x.MsgClass
	}
	return 0
}

func (x *EFrameMsgPushMsgToClientReq) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

// EFrameMsgBroadcastMsgToClient int32 = 5 // 广播消息给玩家
type EFrameMsgBroadcastMsgToClientReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleList []int64 `protobuf:"varint,1,rep,packed,name=RoleList,proto3" json:"RoleList,omitempty"`
	MsgType  int32   `protobuf:"varint,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MsgClass int32   `protobuf:"varint,3,opt,name=MsgClass,proto3" json:"MsgClass,omitempty"`
	MsgData  []byte  `protobuf:"bytes,4,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
}

func (x *EFrameMsgBroadcastMsgToClientReq) Reset() {
	*x = EFrameMsgBroadcastMsgToClientReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EFrameMsgBroadcastMsgToClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EFrameMsgBroadcastMsgToClientReq) ProtoMessage() {}

func (x *EFrameMsgBroadcastMsgToClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EFrameMsgBroadcastMsgToClientReq.ProtoReflect.Descriptor instead.
func (*EFrameMsgBroadcastMsgToClientReq) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{7}
}

func (x *EFrameMsgBroadcastMsgToClientReq) GetRoleList() []int64 {
	if x != nil {
		return x.RoleList
	}
	return nil
}

func (x *EFrameMsgBroadcastMsgToClientReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EFrameMsgBroadcastMsgToClientReq) GetMsgClass() int32 {
	if x != nil {
		return x.MsgClass
	}
	return 0
}

func (x *EFrameMsgBroadcastMsgToClientReq) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

// 转发消息
// EFrameMsgTransMsg             int32 = 6 // 转发消息
type EFrameMsgTransMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgClass    int32  `protobuf:"varint,1,opt,name=MsgClass,proto3" json:"MsgClass,omitempty"`
	MsgType     int32  `protobuf:"varint,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	MsgData     []byte `protobuf:"bytes,3,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
	FromNodeUID int64  `protobuf:"varint,4,opt,name=FromNodeUID,proto3" json:"FromNodeUID,omitempty"` // 消息源服务器
	DestNodeUID int64  `protobuf:"varint,5,opt,name=DestNodeUID,proto3" json:"DestNodeUID,omitempty"` // 消息目的服务器
}

func (x *EFrameMsgTransMsgReq) Reset() {
	*x = EFrameMsgTransMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EFrameMsgTransMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EFrameMsgTransMsgReq) ProtoMessage() {}

func (x *EFrameMsgTransMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EFrameMsgTransMsgReq.ProtoReflect.Descriptor instead.
func (*EFrameMsgTransMsgReq) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{8}
}

func (x *EFrameMsgTransMsgReq) GetMsgClass() int32 {
	if x != nil {
		return x.MsgClass
	}
	return 0
}

func (x *EFrameMsgTransMsgReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *EFrameMsgTransMsgReq) GetMsgData() []byte {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *EFrameMsgTransMsgReq) GetFromNodeUID() int64 {
	if x != nil {
		return x.FromNodeUID
	}
	return 0
}

func (x *EFrameMsgTransMsgReq) GetDestNodeUID() int64 {
	if x != nil {
		return x.DestNodeUID
	}
	return 0
}

type EFrameMsgTransMsgRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EFrameMsgTransMsgRep) Reset() {
	*x = EFrameMsgTransMsgRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_s_frame_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EFrameMsgTransMsgRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EFrameMsgTransMsgRep) ProtoMessage() {}

func (x *EFrameMsgTransMsgRep) ProtoReflect() protoreflect.Message {
	mi := &file_s_frame_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EFrameMsgTransMsgRep.ProtoReflect.Descriptor instead.
func (*EFrameMsgTransMsgRep) Descriptor() ([]byte, []int) {
	return file_s_frame_proto_rawDescGZIP(), []int{9}
}

var File_s_frame_proto protoreflect.FileDescriptor

var file_s_frame_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x62, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x53, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x44, 0x65, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x72, 0x72, 0x44,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x10, 0x53, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x45,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x45, 0x72, 0x72, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x73, 0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x1d, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x5a,
	0x6f, 0x6e, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x5a, 0x6f, 0x6e,
	0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a,
	0x07, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x22, 0x6e, 0x0a, 0x1c, 0x45, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x73, 0x67, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a, 0x1c, 0x45, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x73, 0x67, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x22, 0x85, 0x01, 0x0a, 0x1b, 0x45, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x73,
	0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x73,
	0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x8e, 0x01, 0x0a, 0x20, 0x45, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x73, 0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d,
	0x73, 0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x22, 0xaa, 0x01, 0x0a, 0x14, 0x45, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x73,
	0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x73,
	0x67, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x72,
	0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x49, 0x44, 0x22, 0x16,
	0x0a, 0x14, 0x45, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x62, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_s_frame_proto_rawDescOnce sync.Once
	file_s_frame_proto_rawDescData = file_s_frame_proto_rawDesc
)

func file_s_frame_proto_rawDescGZIP() []byte {
	file_s_frame_proto_rawDescOnce.Do(func() {
		file_s_frame_proto_rawDescData = protoimpl.X.CompressGZIP(file_s_frame_proto_rawDescData)
	})
	return file_s_frame_proto_rawDescData
}

var file_s_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_s_frame_proto_goTypes = []interface{}{
	(*SErrorParams)(nil),                     // 0: pbframe.SErrorParams
	(*SErrorDetailInfo)(nil),                 // 1: pbframe.SErrorDetailInfo
	(*FrameMsgRegisterServerInfoReq)(nil),    // 2: pbframe.FrameMsgRegisterServerInfoReq
	(*FrameMsgRegisterServerInfoRep)(nil),    // 3: pbframe.FrameMsgRegisterServerInfoRep
	(*EFrameMsgServerMsgConvertReq)(nil),     // 4: pbframe.EFrameMsgServerMsgConvertReq
	(*EFrameMsgServerMsgConvertRep)(nil),     // 5: pbframe.EFrameMsgServerMsgConvertRep
	(*EFrameMsgPushMsgToClientReq)(nil),      // 6: pbframe.EFrameMsgPushMsgToClientReq
	(*EFrameMsgBroadcastMsgToClientReq)(nil), // 7: pbframe.EFrameMsgBroadcastMsgToClientReq
	(*EFrameMsgTransMsgReq)(nil),             // 8: pbframe.EFrameMsgTransMsgReq
	(*EFrameMsgTransMsgRep)(nil),             // 9: pbframe.EFrameMsgTransMsgRep
}
var file_s_frame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s_frame_proto_init() }
func file_s_frame_proto_init() {
	if File_s_frame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_s_frame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SErrorParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SErrorDetailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameMsgRegisterServerInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameMsgRegisterServerInfoRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EFrameMsgServerMsgConvertReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EFrameMsgServerMsgConvertRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EFrameMsgPushMsgToClientReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EFrameMsgBroadcastMsgToClientReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EFrameMsgTransMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_s_frame_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EFrameMsgTransMsgRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_s_frame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s_frame_proto_goTypes,
		DependencyIndexes: file_s_frame_proto_depIdxs,
		MessageInfos:      file_s_frame_proto_msgTypes,
	}.Build()
	File_s_frame_proto = out.File
	file_s_frame_proto_rawDesc = nil
	file_s_frame_proto_goTypes = nil
	file_s_frame_proto_depIdxs = nil
}
