// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RdsCsGlobal struct {
	ID      	int32	`redis:"ID"`
	OpenTime	int64	`redis:"OpenTime"`
	DbStatus	int8	`redis:"DbStatus"`
}
