// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RoleBag struct {
	RoleID 	int64	`gorm:"primary_key" json:"role_id"`
	Bag    	[]byte	`gorm:"bag" json:"bag"`
	UpdTime	int64	`gorm:"upd_time" json:"upd_time"`
}
func (t *RoleBag) TableName() string {
	return "role_bag"
}