// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RoleCoin struct {
	RoleID 	int64	`gorm:"primary_key" json:"role_id"`
	Coin   	string	`gorm:"coin" json:"coin"`
	UpdTime	int64	`gorm:"upd_time" json:"upd_time"`
}
func (t *RoleCoin) TableName() string {
	return "role_coin"
}