// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RoleEquip struct {
	RoleID 	int64	`gorm:"primary_key" json:"role_id"`
	Equip  	[]byte	`gorm:"equip" json:"equip"`
	UpdTime	int64	`gorm:"upd_time" json:"upd_time"`
}
func (t *RoleEquip) TableName() string {
	return "role_equip"
}