// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RdsRoleBase struct {
	RoleID     	int64	`redis:"RoleID"`
	UserID     	int64	`redis:"UserID"`
	RoleName   	string	`redis:"RoleName"`
	CreateTime 	int64	`redis:"CreateTime"`
	Level      	int32	`redis:"Level"`
	LoginTime  	int64	`redis:"LoginTime"`
	OfflineTime	int64	`redis:"OfflineTime"`
	UpdTime    	int64	`redis:"UpdTime"`
	DbStatus	int8	`redis:"DbStatus"`
}
