// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RdsRoleBag struct {
	RoleID 	int64	`redis:"RoleID"`
	Bag    	[]byte	`redis:"Bag"`
	UpdTime	int64	`redis:"UpdTime"`
	DbStatus	int8	`redis:"DbStatus"`
}
