// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RoleExtra struct {
	RoleID   	int64	`gorm:"primary_key" json:"role_id"`
	ExtraData	[]byte	`gorm:"extra_data" json:"extra_data"`
	UpdTime  	int64	`gorm:"upd_time" json:"upd_time"`
}
func (t *RoleExtra) TableName() string {
	return "role_extra"
}