// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RdsRoleEquip struct {
	RoleID 	int64	`redis:"RoleID"`
	Equip  	[]byte	`redis:"Equip"`
	UpdTime	int64	`redis:"UpdTime"`
	DbStatus	int8	`redis:"DbStatus"`
}
