// --- this file generated by tools, don't edit it!!!! ---
package ormdef

type RdsRoleExtra struct {
	RoleID   	int64	`redis:"RoleID"`
	ExtraData	[]byte	`redis:"ExtraData"`
	UpdTime  	int64	`redis:"UpdTime"`
	DbStatus	int8	`redis:"DbStatus"`
}
