// --- this file generated by tools, please write your code in custom block ---
package tbobj

import (
	"trcell/pkg/ormdef"
	"trcell/pkg/pborm"
	"google.golang.org/protobuf/proto"
)

type TbCsGlobal struct{
	TableObjOpt
	ormMeta *ormdef.CsGlobal
	// ------------------ customtag1 code begin ---------------------
	// ------------------ customtag1 code end -----------------------
}

// ID
func (tb *TbCsGlobal) GetID() int32 {
	return tb.ormMeta.ID
}
func (tb *TbCsGlobal) SetID(id int32) {
	tb.ormMeta.ID = id
	tb.SetDbStatus(DbStatusUpdate)
}

// OpenTime
func (tb *TbCsGlobal) GetOpenTime() int64 {
	return tb.ormMeta.OpenTime
}
func (tb *TbCsGlobal) SetOpenTime(openTime int64) {
	tb.ormMeta.OpenTime = openTime
	tb.SetDbStatus(DbStatusUpdate)
}

func (tb *TbCsGlobal) DumpToPbOrm() *pborm.CsGlobal {
	tb.Serialize()
	pbObj := &pborm.CsGlobal{
		ID: tb.ormMeta.ID,
		OpenTime: tb.ormMeta.OpenTime,
	}
	pbObj.DbStatus = int32(tb.dbStatus)
	return pbObj
}
func (tb *TbCsGlobal) LoadFromPbOrm(obj *pborm.CsGlobal) {
	tb.ormMeta.ID = obj.ID
	tb.ormMeta.OpenTime = obj.OpenTime
	tb.dbStatus = int8(obj.DbStatus)
	tb.Unserialize()
}
func NewTbCsGlobal() *TbCsGlobal {
	newObj := &TbCsGlobal{
		ormMeta: &ormdef.CsGlobal{
			ID: 0,
			OpenTime: 0,
		},
	}
	// ------------------ customtag2 code begin ---------------------
	// ------------------ customtag2 code end -----------------------
	return newObj
}
func (tb *TbCsGlobal) Serialize() {
	// ------------------ customtag3 code begin ---------------------
	// ------------------ customtag3 code end -----------------------
}
func (tb *TbCsGlobal) Unserialize() {
	// ------------------ customtag4 code begin ---------------------
	// ------------------ customtag4 code end -----------------------
}
func (tb *TbCsGlobal) ToBytes() ([]byte, error) {
	pbObj := tb.DumpToPbOrm()
	return proto.Marshal(pbObj)
}
func (tb *TbCsGlobal) FromBytes(data []byte) error {
	pbOrm := &pborm.CsGlobal{}
	err := proto.Unmarshal(data, pbOrm)
	if err != nil {
		return err
	}
	tb.LoadFromPbOrm(pbOrm)
	return nil
}
func (tb *TbCsGlobal) GetOrmMeta() *ormdef.CsGlobal {
	return tb.ormMeta
}
// ------------------ customtag5 code begin ---------------------
// ------------------ customtag5 code end -----------------------
