// --- this file generated by tools, please write your code in custom block ---
package tbobj

import (
	"trcell/pkg/ormdef"
	"trcell/pkg/pborm"

	"google.golang.org/protobuf/proto"
)

type TbRoleExtra struct {
	TableObjOpt
	ormMeta *ormdef.RoleExtra
	// ------------------ customtag1 code begin ---------------------
	extraData ITableBlobField
	// ------------------ customtag1 code end -----------------------
}

// RoleID
func (tb *TbRoleExtra) GetRoleID() int64 {
	return tb.ormMeta.RoleID
}
func (tb *TbRoleExtra) SetRoleID(roleID int64) {
	tb.ormMeta.RoleID = roleID
	tb.SetDbStatus(DbStatusUpdate)
}

// ExtraData
func (tb *TbRoleExtra) GetExtraData() []byte {
	return tb.ormMeta.ExtraData
}
func (tb *TbRoleExtra) SetExtraData(extraData []byte) {
	tb.ormMeta.ExtraData = extraData
	tb.SetDbStatus(DbStatusUpdate)
}

// UpdTime
func (tb *TbRoleExtra) GetUpdTime() int64 {
	return tb.ormMeta.UpdTime
}
func (tb *TbRoleExtra) SetUpdTime(updTime int64) {
	tb.ormMeta.UpdTime = updTime
	tb.SetDbStatus(DbStatusUpdate)
}

func (tb *TbRoleExtra) DumpToPbOrm() *pborm.RoleExtra {
	tb.Serialize()
	pbObj := &pborm.RoleExtra{
		RoleID:    tb.ormMeta.RoleID,
		ExtraData: tb.ormMeta.ExtraData,
		UpdTime:   tb.ormMeta.UpdTime,
	}
	pbObj.ExtraData = make([]byte, len(tb.ormMeta.ExtraData))
	copy(pbObj.ExtraData, tb.ormMeta.ExtraData)
	pbObj.DbStatus = int32(tb.dbStatus)
	return pbObj
}
func (tb *TbRoleExtra) LoadFromPbOrm(obj *pborm.RoleExtra) {
	tb.ormMeta.RoleID = obj.RoleID
	tb.ormMeta.ExtraData = obj.ExtraData
	tb.ormMeta.UpdTime = obj.UpdTime
	tb.ormMeta.ExtraData = make([]byte, len(obj.ExtraData))
	copy(tb.ormMeta.ExtraData, obj.ExtraData)
	tb.dbStatus = int8(obj.DbStatus)
	tb.Unserialize()
}
func NewTbRoleExtra() *TbRoleExtra {
	newObj := &TbRoleExtra{
		ormMeta: &ormdef.RoleExtra{
			RoleID:    0,
			ExtraData: make([]byte, 0),
			UpdTime:   0,
		},
	}
	// ------------------ customtag2 code begin ---------------------
	// ------------------ customtag2 code end -----------------------
	return newObj
}
func (tb *TbRoleExtra) Serialize() {
	// ------------------ customtag3 code begin ---------------------
	if tb.extraData != nil {
		tb.SetExtraData(tb.extraData.ToBytes())
	}
	// ------------------ customtag3 code end -----------------------
}
func (tb *TbRoleExtra) Unserialize() {
	// ------------------ customtag4 code begin ---------------------
	if tb.extraData != nil {
		tb.extraData.FromBytes(tb.GetExtraData())
	}
	// ------------------ customtag4 code end -----------------------
}
func (tb *TbRoleExtra) ToBytes() ([]byte, error) {
	pbObj := tb.DumpToPbOrm()
	return proto.Marshal(pbObj)
}
func (tb *TbRoleExtra) FromBytes(data []byte) error {
	pbOrm := &pborm.RoleExtra{}
	err := proto.Unmarshal(data, pbOrm)
	if err != nil {
		return err
	}
	tb.LoadFromPbOrm(pbOrm)
	return nil
}
func (tb *TbRoleExtra) GetOrmMeta() *ormdef.RoleExtra {
	return tb.ormMeta
}

// ------------------ customtag5 code begin ---------------------
func (tb *TbRoleExtra) BindModule(fieldModule ITableBlobField) {
	tb.extraData = fieldModule
}

// ------------------ customtag5 code end -----------------------
