// --- this file generated by tools, please write your code in custom block ---
package tbobj

import (
	"trcell/pkg/ormdef"
	"trcell/pkg/pborm"

	"google.golang.org/protobuf/proto"
)

type TbRoleEquip struct {
	TableObjOpt
	ormMeta *ormdef.RoleEquip
	// ------------------ customtag1 code begin ---------------------
	equipData ITableBlobField
	// ------------------ customtag1 code end -----------------------
}

// RoleID
func (tb *TbRoleEquip) GetRoleID() int64 {
	return tb.ormMeta.RoleID
}
func (tb *TbRoleEquip) SetRoleID(roleID int64) {
	tb.ormMeta.RoleID = roleID
	tb.SetDbStatus(DbStatusUpdate)
}

// Equip
func (tb *TbRoleEquip) GetEquip() []byte {
	return tb.ormMeta.Equip
}
func (tb *TbRoleEquip) SetEquip(equip []byte) {
	tb.ormMeta.Equip = equip
	tb.SetDbStatus(DbStatusUpdate)
}

// UpdTime
func (tb *TbRoleEquip) GetUpdTime() int64 {
	return tb.ormMeta.UpdTime
}
func (tb *TbRoleEquip) SetUpdTime(updTime int64) {
	tb.ormMeta.UpdTime = updTime
	tb.SetDbStatus(DbStatusUpdate)
}

func (tb *TbRoleEquip) DumpToPbOrm() *pborm.RoleEquip {
	tb.Serialize()
	pbObj := &pborm.RoleEquip{
		RoleID:  tb.ormMeta.RoleID,
		Equip:   tb.ormMeta.Equip,
		UpdTime: tb.ormMeta.UpdTime,
	}
	pbObj.Equip = make([]byte, len(tb.ormMeta.Equip))
	copy(pbObj.Equip, tb.ormMeta.Equip)
	pbObj.DbStatus = int32(tb.dbStatus)
	return pbObj
}
func (tb *TbRoleEquip) LoadFromPbOrm(obj *pborm.RoleEquip) {
	tb.ormMeta.RoleID = obj.RoleID
	tb.ormMeta.Equip = obj.Equip
	tb.ormMeta.UpdTime = obj.UpdTime
	tb.ormMeta.Equip = make([]byte, len(obj.Equip))
	copy(tb.ormMeta.Equip, obj.Equip)
	tb.dbStatus = int8(obj.DbStatus)
	tb.Unserialize()
}
func NewTbRoleEquip() *TbRoleEquip {
	newObj := &TbRoleEquip{
		ormMeta: &ormdef.RoleEquip{
			RoleID:  0,
			Equip:   make([]byte, 0),
			UpdTime: 0,
		},
	}
	// ------------------ customtag2 code begin ---------------------
	// ------------------ customtag2 code end -----------------------
	return newObj
}
func (tb *TbRoleEquip) Serialize() {
	// ------------------ customtag3 code begin ---------------------
	if tb.equipData != nil {
		tb.SetEquip(tb.equipData.ToBytes())
	}
	// ------------------ customtag3 code end -----------------------
}
func (tb *TbRoleEquip) Unserialize() {
	// ------------------ customtag4 code begin ---------------------
	if tb.equipData != nil {
		tb.equipData.FromBytes(tb.GetEquip())
	}
	// ------------------ customtag4 code end -----------------------
}
func (tb *TbRoleEquip) ToBytes() ([]byte, error) {
	pbObj := tb.DumpToPbOrm()
	return proto.Marshal(pbObj)
}
func (tb *TbRoleEquip) FromBytes(data []byte) error {
	pbOrm := &pborm.RoleEquip{}
	err := proto.Unmarshal(data, pbOrm)
	if err != nil {
		return err
	}
	tb.LoadFromPbOrm(pbOrm)
	return nil
}
func (tb *TbRoleEquip) GetOrmMeta() *ormdef.RoleEquip {
	return tb.ormMeta
}

// ------------------ customtag5 code begin ---------------------
func (tb *TbRoleEquip) BindModule(fieldModule ITableBlobField) {
	tb.equipData = fieldModule
}

// ------------------ customtag5 code end -----------------------
