// --- this file generated by tools, please write your code in custom block ---
package tbobj

import (
	"trcell/pkg/ormdef"
	"trcell/pkg/pborm"
	"google.golang.org/protobuf/proto"
)

type TbRoleBase struct{
	TableObjOpt
	ormMeta *ormdef.RoleBase
	// ------------------ customtag1 code begin ---------------------
	// ------------------ customtag1 code end -----------------------
}

// RoleID
func (tb *TbRoleBase) GetRoleID() int64 {
	return tb.ormMeta.RoleID
}
func (tb *TbRoleBase) SetRoleID(roleID int64) {
	tb.ormMeta.RoleID = roleID
	tb.SetDbStatus(DbStatusUpdate)
}

// UserID
func (tb *TbRoleBase) GetUserID() int64 {
	return tb.ormMeta.UserID
}
func (tb *TbRoleBase) SetUserID(userID int64) {
	tb.ormMeta.UserID = userID
	tb.SetDbStatus(DbStatusUpdate)
}

// RoleName
func (tb *TbRoleBase) GetRoleName() string {
	return tb.ormMeta.RoleName
}
func (tb *TbRoleBase) SetRoleName(roleName string) {
	tb.ormMeta.RoleName = roleName
	tb.SetDbStatus(DbStatusUpdate)
}

// CreateTime
func (tb *TbRoleBase) GetCreateTime() int64 {
	return tb.ormMeta.CreateTime
}
func (tb *TbRoleBase) SetCreateTime(createTime int64) {
	tb.ormMeta.CreateTime = createTime
	tb.SetDbStatus(DbStatusUpdate)
}

// Level
func (tb *TbRoleBase) GetLevel() int32 {
	return tb.ormMeta.Level
}
func (tb *TbRoleBase) SetLevel(level int32) {
	tb.ormMeta.Level = level
	tb.SetDbStatus(DbStatusUpdate)
}

// LoginTime
func (tb *TbRoleBase) GetLoginTime() int64 {
	return tb.ormMeta.LoginTime
}
func (tb *TbRoleBase) SetLoginTime(loginTime int64) {
	tb.ormMeta.LoginTime = loginTime
	tb.SetDbStatus(DbStatusUpdate)
}

// OfflineTime
func (tb *TbRoleBase) GetOfflineTime() int64 {
	return tb.ormMeta.OfflineTime
}
func (tb *TbRoleBase) SetOfflineTime(offlineTime int64) {
	tb.ormMeta.OfflineTime = offlineTime
	tb.SetDbStatus(DbStatusUpdate)
}

// UpdTime
func (tb *TbRoleBase) GetUpdTime() int64 {
	return tb.ormMeta.UpdTime
}
func (tb *TbRoleBase) SetUpdTime(updTime int64) {
	tb.ormMeta.UpdTime = updTime
	tb.SetDbStatus(DbStatusUpdate)
}

func (tb *TbRoleBase) DumpToPbOrm() *pborm.RoleBase {
	tb.Serialize()
	pbObj := &pborm.RoleBase{
		RoleID: tb.ormMeta.RoleID,
		UserID: tb.ormMeta.UserID,
		RoleName: tb.ormMeta.RoleName,
		CreateTime: tb.ormMeta.CreateTime,
		Level: tb.ormMeta.Level,
		LoginTime: tb.ormMeta.LoginTime,
		OfflineTime: tb.ormMeta.OfflineTime,
		UpdTime: tb.ormMeta.UpdTime,
	}
	pbObj.DbStatus = int32(tb.dbStatus)
	return pbObj
}
func (tb *TbRoleBase) LoadFromPbOrm(obj *pborm.RoleBase) {
	tb.ormMeta.RoleID = obj.RoleID
	tb.ormMeta.UserID = obj.UserID
	tb.ormMeta.RoleName = obj.RoleName
	tb.ormMeta.CreateTime = obj.CreateTime
	tb.ormMeta.Level = obj.Level
	tb.ormMeta.LoginTime = obj.LoginTime
	tb.ormMeta.OfflineTime = obj.OfflineTime
	tb.ormMeta.UpdTime = obj.UpdTime
	tb.dbStatus = int8(obj.DbStatus)
	tb.Unserialize()
}
func NewTbRoleBase() *TbRoleBase {
	newObj := &TbRoleBase{
		ormMeta: &ormdef.RoleBase{
			RoleID: 0,
			UserID: 0,
			RoleName: "",
			CreateTime: 0,
			Level: 0,
			LoginTime: 0,
			OfflineTime: 0,
			UpdTime: 0,
		},
	}
	// ------------------ customtag2 code begin ---------------------
	// ------------------ customtag2 code end -----------------------
	return newObj
}
func (tb *TbRoleBase) Serialize() {
	// ------------------ customtag3 code begin ---------------------
	// ------------------ customtag3 code end -----------------------
}
func (tb *TbRoleBase) Unserialize() {
	// ------------------ customtag4 code begin ---------------------
	// ------------------ customtag4 code end -----------------------
}
func (tb *TbRoleBase) ToBytes() ([]byte, error) {
	pbObj := tb.DumpToPbOrm()
	return proto.Marshal(pbObj)
}
func (tb *TbRoleBase) FromBytes(data []byte) error {
	pbOrm := &pborm.RoleBase{}
	err := proto.Unmarshal(data, pbOrm)
	if err != nil {
		return err
	}
	tb.LoadFromPbOrm(pbOrm)
	return nil
}
func (tb *TbRoleBase) GetOrmMeta() *ormdef.RoleBase {
	return tb.ormMeta
}
// ------------------ customtag5 code begin ---------------------
// ------------------ customtag5 code end -----------------------
