// --- this file generated by tools, please write your code in custom block ---
package tbobj

import (
	"trcell/pkg/ormdef"
	"trcell/pkg/pborm"

	"google.golang.org/protobuf/proto"
)

type TbRoleCoin struct {
	TableObjOpt
	ormMeta *ormdef.RoleCoin
	// ------------------ customtag1 code begin ---------------------
	coinData ITableBlobField
	// ------------------ customtag1 code end -----------------------
}

// RoleID
func (tb *TbRoleCoin) GetRoleID() int64 {
	return tb.ormMeta.RoleID
}
func (tb *TbRoleCoin) SetRoleID(roleID int64) {
	tb.ormMeta.RoleID = roleID
	tb.SetDbStatus(DbStatusUpdate)
}

// Coin
func (tb *TbRoleCoin) GetCoin() string {
	return tb.ormMeta.Coin
}
func (tb *TbRoleCoin) SetCoin(coin string) {
	tb.ormMeta.Coin = coin
	tb.SetDbStatus(DbStatusUpdate)
}

// UpdTime
func (tb *TbRoleCoin) GetUpdTime() int64 {
	return tb.ormMeta.UpdTime
}
func (tb *TbRoleCoin) SetUpdTime(updTime int64) {
	tb.ormMeta.UpdTime = updTime
	tb.SetDbStatus(DbStatusUpdate)
}

func (tb *TbRoleCoin) DumpToPbOrm() *pborm.RoleCoin {
	tb.Serialize()
	pbObj := &pborm.RoleCoin{
		RoleID:  tb.ormMeta.RoleID,
		Coin:    tb.ormMeta.Coin,
		UpdTime: tb.ormMeta.UpdTime,
	}
	pbObj.DbStatus = int32(tb.dbStatus)
	return pbObj
}
func (tb *TbRoleCoin) LoadFromPbOrm(obj *pborm.RoleCoin) {
	tb.ormMeta.RoleID = obj.RoleID
	tb.ormMeta.Coin = obj.Coin
	tb.ormMeta.UpdTime = obj.UpdTime
	tb.dbStatus = int8(obj.DbStatus)
	tb.Unserialize()
}
func NewTbRoleCoin() *TbRoleCoin {
	newObj := &TbRoleCoin{
		ormMeta: &ormdef.RoleCoin{
			RoleID:  0,
			Coin:    "",
			UpdTime: 0,
		},
	}
	// ------------------ customtag2 code begin ---------------------
	newObj.coinData = nil
	newObj.SetCoin("{}")
	// ------------------ customtag2 code end -----------------------
	return newObj
}
func (tb *TbRoleCoin) Serialize() {
	// ------------------ customtag3 code begin ---------------------
	if tb.coinData != nil {
		data := tb.coinData.ToBytes()
		if data != nil {
			tb.SetCoin(string(data))
		} else {
			tb.SetCoin("{}")
		}
	}
	// ------------------ customtag3 code end -----------------------
}
func (tb *TbRoleCoin) Unserialize() {
	// ------------------ customtag4 code begin ---------------------
	if len(tb.GetCoin()) > 0 {
		if tb.coinData != nil {
			tb.coinData.FromBytes([]byte(tb.GetCoin()))
		}
	} else {
		if tb.coinData != nil {
			tb.coinData.FromBytes([]byte("{}"))
		}
	}
	// ------------------ customtag4 code end -----------------------
}
func (tb *TbRoleCoin) ToBytes() ([]byte, error) {
	pbObj := tb.DumpToPbOrm()
	return proto.Marshal(pbObj)
}
func (tb *TbRoleCoin) FromBytes(data []byte) error {
	pbOrm := &pborm.RoleCoin{}
	err := proto.Unmarshal(data, pbOrm)
	if err != nil {
		return err
	}
	tb.LoadFromPbOrm(pbOrm)
	return nil
}
func (tb *TbRoleCoin) GetOrmMeta() *ormdef.RoleCoin {
	return tb.ormMeta
}

// ------------------ customtag5 code begin ---------------------
func (tb *TbRoleCoin) BindModule(fieldModule ITableBlobField) {
	tb.coinData = fieldModule
}

// ------------------ customtag5 code end -----------------------
